In [ ]:
# Using Numpy
import numpy as np

arr = np.array([[[1, 3, 7], [4, 5, 10]]])

print("Array 1:", arr)

arr2 = np.array([[[1, 2, 3], [3, 5, 6]]])

print("Array 2:", arr2)

add = arr + arr2
print("Sum of 2 Arrays:", add)
print("Shape of Array 1:", )

Array 1: [[[ 1  3  7]
  [ 4  5 10]]]
Array 2: [[[1 2 3]
  [3 5 6]]]
Sum of 2 Arrays: [[[ 2  5 10]
  [ 7 10 16]]]


In [ ]:
# Using Lists
mat1 = [
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]
]
mat2 = [
[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]
]
rows = len(mat1)
cols = len(mat1[0])
mat_sum = [[0 for _ in range(cols)] for _ in range(rows)]
for i in range(rows):
  for j in range(cols):
   mat_sum[i][j] = mat1[i][j] + mat2[i][j]
  print("Resultant Matrix Sum:")
  for row in mat_sum:
    print(row)

Resultant Matrix Sum (Lists):
[11, 22, 33, 44]
[0, 0, 0, 0]
[0, 0, 0, 0]
Resultant Matrix Sum (Lists):
[11, 22, 33, 44]
[55, 66, 77, 88]
[0, 0, 0, 0]
Resultant Matrix Sum (Lists):
[11, 22, 33, 44]
[55, 66, 77, 88]
[99, 110, 121, 132]
