In [ ]:
import numpy as np

arr = np.array([[[1, 3, 7], [4, 5, 10]]])

print("Array 1:", arr)

arr2 = np.array([[[1, 2, 3], [3, 5, 6]]])

print("Array 2:", arr2)

add = arr + arr2
print("Sum of 2 Arrays:", add)
print("Shape of Array 1:", )

Array 1: [[[ 1  3  7]
  [ 4  5 10]]]
Array 2: [[[1 2 3]
  [3 5 6]]]
Sum of 2 Arrays: [[[ 2  5 10]
  [ 7 10 16]]]
