In [35]:
import numpy as np

arr = np.array([[[1, 2, 6], [78, 12, 0]]])
arr2 = np.array([[[1, 34, 1], [13, 16, 24]]])

sum = arr + arr2

print("Sum of Arrays are:", sum)
print("2nd column in Array 1 is:", arr[0, 1])
print(arr[0, 0])
# Copying Sum
x = sum.copy()
print(x)

# Shapes of Arrays
print("Shape of Sum:", sum.shape)
# Creating Arrays Using ndmin
arrn = np.array([17, 34, 132], ndmin = 5)
print(arrn)

arrnr = arrn.reshape(3)
print(arrnr)
sarr = np.array_split(arr, 3)
print(sarr)

Sum of Arrays are: [[[ 2 36  7]
  [91 28 24]]]
2nd column in Array 1 is: [78 12  0]
[1 2 6]
[[[ 2 36  7]
  [91 28 24]]]
Shape of Sum: (1, 2, 3)
[[[[[ 17  34 132]]]]]
[ 17  34 132]
[array([[[ 1,  2,  6],
        [78, 12,  0]]]), array([], shape=(0, 2, 3), dtype=int64), array([], shape=(0, 2, 3), dtype=int64)]


In [37]:
number = []
x = float(input("Enter 5 Numbers:"))
y = float(input("Enter the Number you want:"))
for x in range(1, 6):
    number.append(x)
    if y is in number:
        print("Your Number is:", y)
    else:
        print() 

SyntaxError: invalid syntax (3730274289.py, line 6)